# Generated by cpp11: do not edit by hand

packed_rtree_create <- function(rct, node_size) {
  .Call(`_rtree_packed_rtree_create`, rct, node_size)
}

packed_rtree_query <- function(tree_sexp, rct) {
  .Call(`_rtree_packed_rtree_query`, tree_sexp, rct)
}
